### ISSUE TITLE
Project throws exception when run out of the box

### ISSUE THREAD

**Issue by ldub** [alexkim205/Google-Drive-Desktop#7]
Repro:

```
$ git clone git@github.com:alexkim205/Google-Drive-Electron.git
$ cd Google-Drive-Electron
$ npm i
$ npm run package-mac
```
then open in finder, and run `Google Drive Electron.app`

Result:

![image](https://user-images.githubusercontent.com/3114081/48161052-791d5900-e28e-11e8-96ae-1b2bbda36b77.png)
```
Uncaught Exception:
Error: Cannot find module './build/javascripts/mainwindow'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/Users/lev/dev/foss/Google-Drive-Electron/release-builds/Google Drive Electron-darwin-x64/Google Drive Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/lev/dev/foss/Google-Drive-Electron/release-builds/Google Drive Electron-darwin-x64/Google Drive Electron.app/Contents/Resources/app/app.js:5:30)
    at Object.<anonymous> (/Users/lev/dev/foss/Google-Drive-Electron/release-builds/Google Drive Electron-darwin-x64/Google Drive Electron.app/Contents/Resources/app/app.js:23:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

Environment info:
```
MacOS: 10.14
Node : v8.11.4
NPM  : v5.6.0
```

**Comment by ldub** [comment]
`npm run start` also doesnt work:

```
λ npm run start

> gdelectron@0.0.3 start /Users/lev/dev/foss/Google-Drive-Electron
> gulp build && electron .

[13:14:13] Using gulpfile ~/dev/foss/Google-Drive-Electron/gulpfile.js
[13:14:13] Task never defined: build
[13:14:13] To list available tasks, try running: gulp --tasks
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gdelectron@0.0.3 start: `gulp build && electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gdelectron@0.0.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lev/.npm/_logs/2018-11-07T21_14_13_704Z-debug.log
```


running `gulp` works fine though.

**Comment by alexkim205** [comment]
It looks like electron can't find `./build/javascripts/mainwindow` because it's looking in the wrong root folder? I'm thinking of fixing this by removing gulp, sass, and pug from this so that instead of fetching files from the build folder, I can just import js and html files relatively.
